### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by ggydush-fn** [MAESTRO-Pool/website#7]
# TODO 
- [x] Update logo in top left to match main logo (stroke width is off)
- [x] Add delegation popup (delegation button doesn't do anything)
- [x] Update landing page to show non-profit we are currently donating to
- [x] Prototype some blog carousel for the landing page
- [x] Would be nice if blog preview looked a little better (i.e. images)
- [x] Add first blog post
